#!/bin/bash
# Get all process IDs that match the window class of "Minecraft"
pids=$(xdotool search --class "Minecraft")

# Loop them to find the valid window
for pid in $pids; do
  name=$(xdotool getwindowname $pid)

  if [[ $name == *"Minecraft"* ]]; then
    # Convert decimal PID to hexadecimal
    window_id=$(printf 0x"%x\n" $pid)

    # Clicker Loop
    while :
    do
    # Check if window is active, if so stop clicking
      if [ "$(xdotool getwindowfocus)" -eq "$pid" ]; then
        exit 0
      fi
      
      xdotool click  --window $window_id 1
      sleep 1
    done
  fi
done
